#!/bin/bash
# Quick-start guide for Lineage demonstrations

echo "╔════════════════════════════════════════════════════════════╗"
echo "║          LINEAGE SYSTEM DEMONSTRATION QUICK-START          ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "Three executable demonstrations are ready:"
echo ""
echo "1. MAIN BINARY (Recommended starting point)"
echo "   └─ cargo run --bin demo"
echo "      Shows: Complete lifecycle with 3 phases"
echo "      Time:  ~10 seconds"
echo ""
echo "2. LIFECYCLE EXAMPLE (Detailed walkthrough)"
echo "   └─ cargo run --example lifecycle_demo"
echo "      Shows: Birth → Health → Strain → Analysis"
echo "      Time:  ~8 seconds with pauses"
echo ""
echo "3. MORTALITY EXAMPLE (Dramatic conclusion)"
echo "   └─ cargo run --example mortality"
echo "      Shows: The inexorable path to death"
echo "      Time:  ~6 seconds"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "What to look for in the output:"
echo ""
echo "  Energy Bar:   Shows remaining energy (decreases only)"
echo "  Damage Bar:   Shows accumulated scars (increases only)"
echo "  Capacity:     Functional capacity (100 minus damage)"
echo "  Status:       🟢 ALIVE or ⚫ DEAD"
echo ""
echo "Key insight: Watch as damage increases task costs."
echo "            Early damage compounds across the entire lifetime."
echo "            Energy exhaustion is inevitable."
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "To run the demonstrations:"
echo ""
echo "   cd D:\\Projects\\Lineage"
echo ""
echo "Then pick one:"
echo "   cargo run --bin demo"
echo "   cargo run --example lifecycle_demo"
echo "   cargo run --example mortality"
echo ""
echo "Each time you run one, you'll see a slightly different outcome"
echo "(different failure types, different damage amounts), but the"
echo "fundamental truth remains: entropy wins, energy depletes, death"
echo "approaches."
echo ""
echo "═══════════════════════════════════════════════════════════════════"
